name: Zip studies on push to master branch
on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - zip-study-on-push-github-action
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
