name: Zip studies on push to master branch
on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - zip-study-on-push-github-action
    #TODO add back paths:
    #  - 'public/**'
jobs:
  zip_studies:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        echo ${{ steps.files.outputs.all }}
        exit 0
    - run: |
        #echo $(echo "${{ steps.files.outputs.all }}" | awk 'BEGIN { RS=" "; FS="/"; ORS=" " } { set[$2]++ } END { for (dir in set) { print dir } }')
        echo ##[set-output name=unique_studies_list;]$(echo "${{ steps.files.outputs.all }}" | awk 'BEGIN { RS=" "; FS="/"; ORS=" " } { set[$2]++ } END { for (dir in set) { print dir } }')
        exit 0
      id: unique_studies
    - run: |
        echo ${{ steps.unique_studies.outputs.unique_studies_list }}
        exit 1
    - run: |
        for changed_study in ${{ steps.unique_studies.outputs.unique_studies_list }}; do
          echo "Do something with this ${changed_study}."
        done
    - uses: actions/checkout@master
    - name: Compress action step
      uses: master-atul/tar-action@v1.0.2
      id: compress
      with:
        command: c
        cwd: ./public
        files: |
          ./acbc_mskcc_2015
        outPath: acbc_mskcc_2015.tar.gz
