name: Zip studies on push to master branch
on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - zip-study-on-push-github-action
    #TODO add back paths:
    #  - 'public/**'
jobs:
  zip_studies:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: | # TODO remove step
        echo ${{ steps.files.outputs.all }}
        exit 0
    - run: |
        echo "##[set-output name=unique_studies_list;]$(echo "${{ steps.files.outputs.all }}" | awk 'BEGIN { RS=" "; FS="/"; ORS=" " } { set[$2]++ } END { for (dir in set) { print dir } }')"
        exit 0
      id: unique_studies
    - run: | # TODO remove step
        echo ${{ steps.unique_studies.outputs.unique_studies_list }}
        exit 0
    - run: |
        pwd
        cd ./public
        pwd
        for changed_study in ${{ steps.unique_studies.outputs.unique_studies_list }}; do
          echo "Compressing this study: ${changed_study}."
          tar -czvf ${changed_study}.tar.gz ${changed_study}
        done
        ls -l .
        cd ../
        pwd
